### ISSUE TITLE
Currency info not loading

### ISSUE THREAD

**Issue by pomkos** [matteodanelli/MMM-cryptocurrency#38] opened 2018-03-13 04:04 UTC
Hello,

Thanks for creating this module!

I installed this module today with the following config:

```
{
        module: "MMM-cryptocurrency",
        position: "bottom bar",
        config: {
                currency: ['ethereum', 'bitcoin'],
                conversion: 'EUR',
                showUSD: false,
                headers: ['change24h', 'change1h', 'change7d'],
                displayType: 'detail',
                showGraphs: false,
                limit: '1200',
        }
},
```
But unfortunately [it's not displaying the information](https://i.imgur.com/37ISFlP.png). It does get the chart going, but nothing more. This is on MM 5.7.1. The only other modules I have is EmbedYouTube and mrxworktraffic. Any ideas?

**Comment by matteodanelli** [comment] 2018-03-17 13:57
Hi,
I'm looking to this issue but I cannot reproduce. Can you open the *developer tools* of the browser and see if there is something wrong?
Where are you deploying the module? Raspberry? Which version?

Let me know, so I can help you! :)

**Comment by pomkos** [comment] 2018-03-19 15:06
Thanks for looking into this!

I have MM manually installed into Ubuntu 17 and run as a server, and then my raspberry pi 3 and an ipad to just load up the appropriate webpage. This is what the web page console shows: https://justpaste.it/1ihe3

Apparently cryptocurrency is receiving weather information instead?

> module.js:154 MMM-cryptocurrency received a module notification: CURRENTWEATHER_DATA from sender: currentweather

**Comment by pomkos** [comment] 2018-03-19 15:06
Whoops, wrong button clicked.

**Comment by Zdenekslezak** [comment] 2018-08-22 12:40
Hey guys, 

I have the same problem, MMM doesnt show any info, my config below 

var config = {
        address: "localhost", // Address to listen on, can be:
                              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                              // - another specific IPv4/6 to listen on a specific interface
                              // - "", "0.0.0.0", "::" to listen on any interface
                              // Default, when address config is left out, is "localhost"
        port: 8080,
        ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
                                                               // or add a specific IPv4 of 192.168.1.5 :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

        language: "cs",
        timeFormat: 24,
        units: "metric",

        modules: [
                {
                        module: "alert",
                },
                {
                        module: "updatenotification",
                        position: "bottom_bar"
                },
                {
                        module: "clock",
                        position: "top_left"
                },
                {
                        module: "calendar",
                        header: "Pracovní kalendář",
                        position: "top_left",
                        config: {
                                fetchInterval: "1000",
                                animationSpeed: "0",
                                timeFormat: "absolute",
                                        calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "URL"
                                        }
                                ]
                        }
                },
                 {
                        module: "calendar",
                        header: "Osobní kalendář",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "url"
                                        }
                                ]
                        }
                },
                {
                        module: "currentweather",
                        position: "top_right",
                        config: {
                                location: "Praha",
                                locationID: "3067696",  //ID from http://www.openweathermap.org/help/city_list.txt
                                appid: "ID"
                        }
                },
                                {
                        module: "MMM-cryptocurrency",
                        position: "top_right",
                        config: {
                             currency: ['ethereum', 'bitcoin'],
                             conversion: 'EUR',
                             showUSD: false,
                             headers: ['change24h', 'change1h', 'change7d'],
                             displayType: 'logoWithChanges',
                             showGraphs: true
                        }
                },
                {
                        module: "weatherforecast",
                        position: "top_right",
                        header: "Předpověď počasí",
                        config: {
                                location: "Praha",
                                locationID: "3067696",  //ID from http://www.openweathermap.org/help/city_list.txt
                                appid: "id"
                        }
                },
                {
                        module: "newsfeed",
                        position: "bottom_bar",
                        config: {
                                feeds: [
                                        {
                                                title: "iDnes.cz",
                                                url: "http://servis.idnes.cz/rss.aspx?c=zpravodaj"
                                        }
                                ],
                                showSourceTitle: true,
                                showPublishDate: true
                        }
                },
        ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by VladimirPal** [comment] 2020-03-06 23:59
```
{
  statusCode: 410,
  error: 'Gone',
  message: 'WARNING: This API is now offline. Please switch to the new CoinMarketCap API.(https://pro.coinmarketcap.com/migrate/)'
}
```
Legacy Public API was officially superseded by the new

**Comment by matteodanelli** [comment] 2020-03-11 20:13
> ```
> {
>   statusCode: 410,
>   error: 'Gone',
>   message: 'WARNING: This API is now offline. Please switch to the new CoinMarketCap API.(https://pro.coinmarketcap.com/migrate/)'
> }
> ```
> 
> Legacy Public API was officially superseded by the new

It should be fixed now.

**Closed** 2020-03-14 20:54 UTC
